language: android
# jdk: oraclejdk8 # Solves #699 https://github.com/OneBusAway/onebusaway-android/commit/7a88700b68864dd780cb4900d7a07f3cd7411a8c
# Turn off caching to avoid any caching problems
# cache: false

env:
  global:
    - ADB_INSTALL_TIMEOUT=8 # 8 minutes (2 minutes by default)

android:
  components:
    - tools
    - platform-tools
    - build-tools-23.0.2
    - android-23
    - extra-google-m2repository
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-19

before_script:
  - echo no | android create avd --force -n test -t android-19 --abi armeabi-v7a
  - emulator -avd test -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell settings put global window_animation_scale 0 &
  - adb shell settings put global transition_animation_scale 0 &
  - adb shell settings put global animator_duration_scale 0 &
  - adb shell input keyevent 82 &

script:
   - ./gradlew build checkstyle test connectedCheck
