language: android
jdk: oraclejdk7

android:
  components:
    - tools
    - tools # See https://github.com/travis-ci/travis-ci/issues/6040#issuecomment-219367943
    - platform-tools
    - build-tools-23.0.2
    - android-23
    - extra-android-support
    - extra-google-m2repository
    - extra-android-m2repository

script:
   - ./gradlew build test